version: 0.2

env:
  variables:
    S3_BUCKET: "team-notes-pro-frontend-853696859325"
    CLOUDFRONT_DISTRIBUTION_ID: "E3HOSF1U0C2PIG"
  parameter-store:
    VITE_API_URL:              "/team-notes-pro/vite-api-url"
    VITE_COGNITO_USER_POOL_ID: "/team-notes-pro/cognito-user-pool-id"
    VITE_COGNITO_CLIENT_ID:    "/team-notes-pro/cognito-client-id"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci --prefix $CODEBUILD_SRC_DIR/team-notes-pro/frontend

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/team-notes-pro/frontend && VITE_API_URL=$VITE_API_URL VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID npm run build

  post_build:
    commands:
      - aws s3 sync $CODEBUILD_SRC_DIR/team-notes-pro/frontend/dist/ s3://$S3_BUCKET --delete --exclude "index.html" --cache-control "public,max-age=31536000,immutable"
      - aws s3 cp $CODEBUILD_SRC_DIR/team-notes-pro/frontend/dist/index.html s3://$S3_BUCKET/index.html --cache-control "no-cache,no-store,must-revalidate" --content-type "text/html"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" --query 'Invalidation.Id' --output text
