version: 0.2

env:
  variables:
    ECR_REPO_URI: "853696859325.dkr.ecr.us-east-1.amazonaws.com/team-notes-pro"
    ECS_CONTAINER_NAME: "app"
  parameter-store:
    VITE_API_URL:              "/team-notes-pro/vite-api-url"
    VITE_COGNITO_USER_POOL_ID: "/team-notes-pro/cognito-user-pool-id"
    VITE_COGNITO_CLIENT_ID:    "/team-notes-pro/cognito-client-id"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Image tag $IMAGE_TAG"

  build:
    commands:
      - cd team-notes-pro && docker build --build-arg VITE_API_URL=$VITE_API_URL --build-arg VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID --build-arg VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID -t $ECR_REPO_URI:$IMAGE_TAG -t $ECR_REPO_URI:latest .

  post_build:
    commands:
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
